version: '3.2'
services:
  router:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - couchbase-oogway
      - rail-status-tracker

  rail-status-tracker:
    image: rail-status-tracker
    links:
      - couchbase-oogway
    depends_on:
      - couchbase-oogway
#    volumes:
#      - /config-files:/var/anand
    ports:
      - "8080:8080"
      - "8081:8081"

  couchbase-oogway:
    image: hub.id.bskyb.com/couchbase
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "11207:11207"
      - "11210:11210"
      - "11211:11211"

